return zero on success checks

diff --git a/.github/workflows/deploy-production.yml b/.github/workflows/deploy-production.yml
--- a/.github/workflows/deploy-production.yml
+++ b/.github/workflows/deploy-production.yml
@@ -42,8 +42,10 @@ jobs:
           git --no-pager diff --no-patch --raw --exit-code origin/${{ env.ci_branch }}
           if [[ $? != 1 ]]
           then
-              echo "No difference with ${{ env.ci_branch }} branch. Aborting"
-              exit 1
+            echo "No difference with ${{ env.ci_branch }} branch. Aborting"
+            exit 1
+          else
+            exit 0
           fi
 
       - name: Break
